package initdata

// TradePairList is list of trade pairs (also called "coin") used for analysis in this project/app.
var TradePairList = []string{"BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT", "SOLUSDT", "EGLDUSDT",
	"SRMUSDT", "TWTUSDT", "AVAXUSDT", "DOTUSDT", "DOGEUSDT", "SHIBUSDT", "MATICUSDT", "ATOMUSDT", "LTCUSDT",
	"NEARUSDT", "LINKUSDT", "TRXUSDT", "UNIUSDT", "FTTUSDT", "BCHUSDT", "ALGOUSDT", "MANAUSDT", "XLMUSDT",
	"HBARUSDT", "FTMUSDT", "ETCUSDT", "ICPUSDT", "SANDUSDT", "FILUSDT", "VETUSDT", "AXSUSDT", "KLAYUSDT",
	"XMRUSDT", "THETAUSDT", "XTZUSDT", "HNTUSDT", "WAVESUSDT", "EOSUSDT", "IOTAUSDT", "FLOWUSDT", "BTTCUSDT",
	"AAVEUSDT", "CAKEUSDT", "GRTUSDT", "ONEUSDT", "GALAUSDT", "ZECUSDT", "RUNEUSDT", "NEOUSDT", "STXUSDT",
	"QNTUSDT", "XECUSDT", "CHZUSDT", "CELOUSDT", "ENJUSDT", "AMPUSDT", "KSMUSDT", "ARUSDT", "BATUSDT",
	"CRVUSDT", "LRCUSDT", "DASHUSDT", "XEMUSDT", "CVXUSDT", "ROSEUSDT", "TFUELUSDT", "MINAUSDT", "DCRUSDT",
	"SCRTUSDT", "HOTUSDT", "YFIUSDT", "COMPUSDT", "IOTXUSDT", "SXPUSDT", "QTUMUSDT", "BNTUSDT", "ANKRUSDT",
	"RVNUSDT", "UMAUSDT", "RNDRUSDT", "1INCHUSDT", "PAXGUSDT", "OMGUSDT", "BTGUSDT", "GLMRUSDT", "KAVAUSDT",
	"ZILUSDT", "LPTUSDT", "ICXUSDT", "ONTUSDT", "AUDIOUSDT", "WOOUSDT", "SCUSDT", "KNCUSDT", "SNXUSDT",
	"ZENUSDT", "ZRXUSDT", "IOSTUSDT", "SKLUSDT", "SUSHIUSDT", "STORJUSDT", "RENUSDT", "POLYUSDT", "IMXUSDT",
	"HIVEUSDT", "SYSUSDT", "JSTUSDT", "ILVUSDT", "CKBUSDT", "SPELLUSDT", "DYDXUSDT", "FXSUSDT", "FLUXUSDT",
	"PERPUSDT", "PEOPLEUSDT", "ENSUSDT", "DGBUSDT", "OCEANUSDT", "WINUSDT", "INJUSDT", "SUPERUSDT", "FETUSDT",
	"TRIBEUSDT", "CELRUSDT", "LSKUSDT", "PLAUSDT", "POWRUSDT", "PYRUSDT", "YGGUSDT", "C98USDT", "WRXUSDT",
	"DENTUSDT", "XNOUSDT", "RAYUSDT", "COTIUSDT", "API3USDT", "CHRUSDT", "MBLUSDT", "ALICEUSDT", "REQUSDT",
	"ONGUSDT", "BTCSTUSDT", "JOEUSDT", "MDXUSDT", "PUNDIXUSDT", "ANTUSDT", "ARDRUSDT", "MOVRUSDT", "ASTRUSDT",
	"ACHUSDT", "CFXUSDT", "CVCUSDT", "CTSIUSDT", "REEFUSDT", "MBOXUSDT", "RSRUSDT", "BETAUSDT", "ORNUSDT",
	"ALPHAUSDT", "BANDUSDT", "NKNUSDT", "DUSKUSDT", "SUNUSDT", "RIFUSDT", "FUNUSDT", "MASKUSDT", "POLSUSDT",
	"TOMOUSDT", "BAKEUSDT"}
